In [3]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns

In [4]:
ncaa = pd.read_csv('../data/ncaa.csv')
ncaa.head()

,game_play_number,id,sequence_number,type_id,type_text,text,away_score,home_score,period_number,period_display_value,...,lag_qtr,lag_half,athlete_id_2,game_date,game_date_time,coordinate_x_raw,coordinate_y_raw,coordinate_x,coordinate_y,media_id
0,1,4.016376e+17,101899901,615,Jumpball,Jump Ball won by South Carolina,0,0,1,1st Quarter,...,NaN,NaN,NaN,2024-04-07,2024-04-07 15:00:00,25.0,0.0,41.75,0.0,NaN
1,2,4.016376e+17,101905501,572,LayUpShot,Chloe Kitts missed Layup.,0,0,1,1st Quarter,...,1.0,1.0,NaN,2024-04-07,2024-04-07 15:00:00,22.0,1.0,40.75,3.0,NaN
2,3,4.016376e+17,101905502,587,Defensive Rebound,Kate Martin Defensive Rebound.,0,0,1,1st Quarter,...,1.0,1.0,NaN,2024-04-07,2024-04-07 15:00:00,25.0,0.0,-41.75,0.0,NaN
3,4,4.016376e+17,101906101,558,JumpShot,Kate Martin made Three Point Jumper. Assisted ...,3,0,1,1st Quarter,...,1.0,1.0,4898389.0,2024-04-07,2024-04-07 15:00:00,15.0,23.0,-18.75,-10.0,NaN
4,5,4.016376e+17,101907901,558,JumpShot,Raven Johnson missed Jumper.,3,0,1,1st Quarter,...,1.0,1.0,NaN,2024-04-07,2024-04-07 15:00:00,19.0,6.0,35.75,6.0,NaN

In [3]:
ncaa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1908679 entries, 0 to 1908678
Data columns (total 61 columns):
 #   Column                           Dtype
---  ------                           -----
 0   game_play_number                 int64
 1   id                               float64
 2   sequence_number                  int64
 3   type_id                          int64
 4   type_text                        object
 5   text                             object
 6   away_score                       int64
 7   home_score                       int64
 8   period_number                    int64
 9   period_display_value             object
 10  clock_display_value              object
 11  scoring_play                     bool
 12  score_value                      int64
 13  team_id                          float64
 14  athlete_id_1                     float64
 15  wallclock                        object
 16  shooting_play                    bool
 17  game_id                          int64
 18  season                           int64
 19  season_type                      int64
 20  home_team_id                     int64
 21  home_team_name                   object
 22  home_team_mascot                 object
 23  home_team_abbrev                 object
 24  home_team_name_alt               object
 25  away_team_id                     int64
 26  away_team_name                   object
 27  away_team_mascot                 object
 28  away_team_abbrev                 object
 29  away_team_name_alt               object
 30  game_spread                      float64
 31  home_favorite                    bool
 32  game_spread_available            bool
 33  home_team_spread                 float64
 34  qtr                              int64
 35  time                             object
 36  clock_minutes                    int64
 37  clock_seconds                    int64
 38  home_timeout_called              bool
 39  away_timeout_called              bool
 40  half                             int64
 41  game_half                        int64
 42  lead_qtr                         float64
 43  lead_half                        float64
 44  start_quarter_seconds_remaining  int64
 45  start_half_seconds_remaining     int64
 46  start_game_seconds_remaining     int64
 47  end_quarter_seconds_remaining    float64
 48  end_half_seconds_remaining       float64
 49  end_game_seconds_remaining       float64
 50  period                           int64
 51  lag_qtr                          float64
 52  lag_half                         float64
 53  athlete_id_2                     float64
 54  game_date                        object
 55  game_date_time                   object
 56  coordinate_x_raw                 float64
 57  coordinate_y_raw                 float64
 58  coordinate_x                     float64
 59  coordinate_y                     float64
 60  media_id                         float64
dtypes: bool(6), float64(18), int64(21), object(16)
memory usage: 811.8+ MB

In [4]:
ncaa['game_date'].value_counts()

game_date
2023-11-06    50866
2024-03-02    41509
2024-01-27    40433
2024-01-06    39837
2024-02-24    38956
              ...
2024-03-31      698
2024-04-05      639
2024-04-07      360
2024-03-27      348
2024-04-06      331
Name: count, Length: 146, dtype: int64

In [5]:
ncaa_fouls = ncaa[ncaa['type_text'].isin(['PersonalFoul','Technical Foul'])]
ncaa_fouls.head()

,game_play_number,id,sequence_number,type_id,type_text,text,away_score,home_score,period_number,period_display_value,...,lag_qtr,lag_half,athlete_id_2,game_date,game_date_time,coordinate_x_raw,coordinate_y_raw,coordinate_x,coordinate_y,media_id
22,23,4.016376e+17,101929501,519,PersonalFoul,Foul on Bree Hall.,10,2,1,1st Quarter,...,1.0,1.0,NaN,2024-04-07,2024-04-07 15:00:00,25.0,0.0,41.75,0.0,NaN
35,36,4.016376e+17,101946501,519,PersonalFoul,Foul on Chloe Kitts.,18,9,1,1st Quarter,...,1.0,1.0,NaN,2024-04-07,2024-04-07 15:00:00,25.0,0.0,41.75,0.0,NaN
44,45,4.016376e+17,101949501,519,PersonalFoul,Foul on Addison O'Grady.,20,9,1,1st Quarter,...,1.0,1.0,NaN,2024-04-07,2024-04-07 15:00:00,25.0,0.0,-41.75,0.0,NaN
47,48,4.016376e+17,101955401,519,PersonalFoul,Foul on Sydney Affolter.,20,9,1,1st Quarter,...,1.0,1.0,NaN,2024-04-07,2024-04-07 15:00:00,25.0,0.0,-41.75,0.0,NaN
55,56,4.016376e+17,101965301,519,PersonalFoul,Foul on Ashlyn Watkins.,20,13,1,1st Quarter,...,1.0,1.0,NaN,2024-04-07,2024-04-07 15:00:00,25.0,0.0,41.75,0.0,NaN

In [6]:
ncaa_fouls['season'].unique()

array([2024])

In [16]:
wnba = pd.read_csv('../data/wnba.csv')
wnba.head()

,game_play_number,id,sequence_number,type_id,type_text,text,away_score,home_score,period_number,period_display_value,...,end_half_seconds_remaining,end_game_seconds_remaining,period,lag_qtr,lag_half,coordinate_x,coordinate_y,game_date,game_date_time,type_abbreviation
0,1,4016204124,4,615,Jumpball,Ezi Magbegor vs. Brionna Jones (Gabby Williams...,0,0,1,1st Quarter,...,1200.0,2400.0,1,NaN,NaN,-2.147484e+08,-214748365,2024-09-03,2024-09-03 19:00:00,NaN
1,2,4016204127,7,62,Bad Pass\nTurnover,Skylar Diggins-Smith bad pass,0,0,1,1st Quarter,...,1160.0,2360.0,1,1.0,1.0,-2.175000e+01,3,2024-09-03,2024-09-03 19:00:00,NaN
2,3,4016204128,8,131,Pullup Jump Shot,DeWanna Bonner misses 36-foot three point pull...,0,0,1,1st Quarter,...,1156.0,2356.0,1,1.0,1.0,6.750000e+00,-10,2024-09-03,2024-09-03 19:00:00,NaN
3,4,4016204129,9,156,Offensive Rebound,DiJonai Carrington offensive rebound,0,0,1,1st Quarter,...,1152.0,2352.0,1,1.0,1.0,6.750000e+00,-10,2024-09-03,2024-09-03 19:00:00,NaN
4,5,40162041210,10,110,Driving Layup Shot,DiJonai Carrington makes driving layup,0,2,1,1st Quarter,...,1139.0,2339.0,1,1.0,1.0,3.875000e+01,-3,2024-09-03,2024-09-03 19:00:00,NaN